### ISSUE TITLE
[Feature Request] cmdstan error reporting from within bebi103.stan.sbc

### ISSUE THREAD

**Issue by muirjm** [justinbois/bebi103#18]
As per slack conversation, currently there is no way to specify an output dir for the .txt files produced by cmdstan inside `bebi103.stan.sbc`. If the top-level function took a dictionary of extra args to pass to `sm.sample()`, then the user could direct the cmdstan output to a more accessible location, making debugging much easier.

**Comment by justinbois** [comment]
This is currently possible with the `sampling_kwargs` kwarg.
