### ISSUE TITLE
stan.sbc() does not handle non-scalar parameters

### ISSUE THREAD

**Issue by tomroesch** [justinbois/bebi103#23]
If a parameter is defined as non-scalar in the stan model for a prior predictive check, it cannot be given as parameter input for `stan.sbc()`. In `stan._get_prior_sd()`, standard deviations are only computed for parameters given as input, but the function `stan.xarray_to_ndarray()` transforms non scalar parameters to have an entry for each element instead.

**Comment by justinbois** [comment]
@tomroesch , I pushed a fix. Can you try it out on your example that was failing before? Let me know if it works, and I'll cut a release.

**Comment by tomroesch** [comment]
Yes, the example works now.
