### ISSUE TITLE
cmdstanpy args changed

### ISSUE THREAD

**Issue by mrazomej** [justinbois/bebi103#24]
CmdStanPy changed arguments for their functions as addressed in [#221](https://github.com/stan-dev/cmdstanpy/issues/221). 
Therefore when calling functions such as `bebi103.stan.sbc` there is an error because of the deprecated `sampling_iters` argument that was changed to `iter_sampling`.

**Comment by mrazomej** [comment]
Also it seems that CmdStanPy removed the attribute `.runset.console_files` since it is not listed anymore in their [documentation](https://cmdstanpy.readthedocs.io/en/latest/api.html#cmdstanpy.stanfit.RunSet.diagnostic_files). I couldn't find information about this change since I didn't find any release notes. But as written now `bebi103.stan.sbc` runs into the following error:
```
AttributeError: 'RunSet' object has no attribute 'console_files'
```
when used with `cmdstanpy=0.9.5`

**Comment by justinbois** [comment]
Fixed in current version.
