### ISSUE TITLE
Release for 2015 edition?

### ISSUE THREAD

**Issue by smsaladi** [justinbois/bebi103#5]
Might be good to tag commit 998b923f4bcec12365391497a6e173c3fd8c5702 as a release, so that API-incompatible changes can be made for the coming year while also making sure old lesson/homework notebooks stay functional.

**Comment by justinbois** [comment]
Ya, tag it.

**Comment by smsaladi** [comment]
I can't -- no write perms on this repo

**Comment by justinbois** [comment]
Done!
