### ISSUE TITLE
Versions > 0.0.12 do not import on some systems

### ISSUE THREAD

**Issue by ajaceves** [justinbois/bebi103#8]
ubuntu 14.04 / Python 3.6.2 installed via anaconda
bebi103 versions > 0.0.12 DO NOT WORK (0.0.16/0.0.15/0.0.14/0.0.13 tested)
bebi103 versions <= 0.0.12 Do work

Error Message:
>>> import bebi103
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aiden/anaconda3/lib/python3.6/site-packages/bebi103/__init__.py", line 7, in <module>
    from . import pm
  File "/home/aiden/anaconda3/lib/python3.6/site-packages/bebi103/pm.py", line 10, in <module>
    from .hotdists import *
  File "/home/aiden/anaconda3/lib/python3.6/site-packages/bebi103/hotdists.py", line 147, in <module>
    class HotConstantDist(pm.ConstantDist):
TypeError: function() argument 1 must be code, not str

Additional Info:
Python modules
alabaster==0.7.10
anaconda-client==1.6.3
anaconda-navigator==1.6.4
anaconda-project==0.6.0
asn1crypto==0.22.0
astroid==1.5.3
astropy==2.0.1
Babel==2.5.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bebi103==0.0.9
biopython==1.69
bitarray==0.8.1
bkcharts==0.2
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.7
boto==2.48.0
Bottleneck==1.2.1
category-encoders==1.2.4
certifi==2016.2.28
cffi==1.10.0
chardet==3.0.4
click==6.7
cloudpickle==0.4.0
clyent==1.2.2
colorama==0.3.9
colorcet==0.9.1
conda==4.3.29
contextlib2==0.5.5
cryptography==1.8.1
cycler==0.10.0
Cython==0.26
cytoolz==0.8.2
dask==0.15.2
datashader==0.6.1
datashape==0.5.4
decorator==4.1.2
distributed==1.18.1
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12.2
Flask-Cors==3.0.3
rope-py3k==0.9.4.post1
scikit-image==0.13.0
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.8
selenium==3.0.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.3
SQLAlchemy==1.1.13
statsmodels==0.8.0
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
terminado==0.6
testpath==0.3
Theano==0.9.0
toolz==0.8.2
tornado==4.5.2
tqdm==4.15.0
traitlets==4.3.2
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.12.2
widgetsnbextension==3.0.2
wrapt==1.10.11
xarray==0.9.6
xlrd==1.1.0
XlsxWriter==0.9.8
xlwt==1.3.0
zict==0.1.2

**Comment by justinbois** [comment]
I don't see PyMC3 installed on that list. Is it installed on your system?

**Comment by ajaceves** [comment]
Pymc3 imports and runs. It shows up in "conda list", and is version 3.1 .  The previous list came from pip --freeze

**Comment by justinbois** [comment]
What happens when you do:

```python
import pymc3
pymc3.__version__
```

**Comment by ajaceves** [comment]
'3.1'

**Comment by ajaceves** [comment]
conda update --all fixed the issue. Thanks for your patience with my bone-headed mistake!

Here are the final package versions that work:

_license                  1.1                      py36_1  
alabaster                 0.7.10           py36h306e16b_0  
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.5            py36h19c0dcd_0  
anaconda-navigator        1.6.9            py36h11ddaaa_0  
anaconda-project          0.8.0            py36h29abdf5_0  
apbs                      1.5                           1    schrodinger
asn1crypto                0.22.0           py36h265ca7c_1  
astroid                   1.5.3            py36hbdb9df2_0  
astropy                   2.0.2            py36ha51211e_4  
babel                     2.5.0            py36h7d14adf_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bebi103                   0.0.16                    <pip>
biopython                 1.69                np113py36_0  
bitarray                  0.8.1            py36h5834eb8_0  
bkcharts                  0.2              py36h735825a_0  
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.0.0            py36h688b259_0  
bokeh                     0.12.10          py36hbb0e44a_0  
boto                      2.48.0           py36h6e4cd66_1  
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h0376d23_1  
ca-certificates           2017.08.26           h1d4fec5_0  
cairo                     1.14.10              haa5651f_5  
category_encoders         1.2.4                    py36_0    conda-forge
certifi                   2017.7.27.1      py36h8b7b77e_0  
cffi                      1.10.0           py36had8d393_1  
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7              py36h5253387_0  
cloudpickle               0.4.0            py36h30f8c20_0  
clyent                    1.2.2            py36h7e57e65_1  
colorama                  0.3.9            py36h489cec4_0  
colorcet                  0.9.1                    py36_0  
conda                     4.3.30           py36h5d9f9f4_0  
conda-env                 2.6.0                h36134e3_1  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.0.3            py36ha225213_1  
curl                      7.55.1               hcb0b314_2  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.26.1           py36h21c49d0_0  
cytoolz                   0.8.2            py36h708bfd4_0  
dask                      0.15.4           py36h31fc154_0  
dask-core                 0.15.4           py36h7045e13_0  
datashader                0.6.2            py36h21a1380_0  
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.10.22              h3b5a359_0  
decorator                 4.1.2            py36hd076ac8_0  
distributed               1.19.1           py36h25f3894_0  
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.4                h6ea4f2b_2  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.5.3            py36h3c761f9_0  
sortedcontainers          1.5.7            py36hdf89491_0  
sphinx                    1.6.3            py36he5f0bdb_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.4            py36hbe6152b_0  
sqlalchemy                1.1.13           py36hfb5efd7_0  
sqlite                    3.20.1               h6d8b0f3_1  
statsmodels               0.8.0            py36h8533d0b_0  
sympy                     1.1.1            py36hc6d1c1c_0  
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.6              py36ha25a19f_0  
testpath                  0.3.1            py36h8cadb63_0  
theano                    0.9.0                    py36_0  
tk                        8.6.7                h5979e9b_1  
toolz                     0.8.2            py36h81f2dff_0  
tornado                   4.5.2            py36h1283b2a_0  
tqdm                      4.19.4           py36ha5a5176_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.2            py36h7da032a_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.4                hc36303a_1  
urllib3                   1.22             py36hbe7ace6_0  
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
werkzeug                  0.12.2           py36hc703753_0  
wheel                     0.29.0           py36he7f4e38_1  
widgetsnbextension        3.0.2            py36hd01bb71_1  
wrapt                     1.10.11          py36h28b7045_0  
xarray                    0.9.6                    py36_0  
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.2            py36h3de1aca_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.3                h55aa19d_2  
yaml                      0.1.7                h014fa73_2  
zeromq                    4.2.2                hb0b69da_1  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               ha838bed_2
