### ISSUE TITLE
Bug in bebi103.viz.im_click()

### ISSUE THREAD

**Issue by julianmwagner** [justinbois/bebi103#9]
Hello,

I was using the module and think I found a bug in the viz.im_click() function. It seems that there is a call to bokeh.layout.row() that should be a call to bokeh.layout**s**.row(). Here is the code to reproduce the error:

`im = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
bokeh.io.show(bebi103.viz.im_click(im))`

The error is as follows:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-ba1d2fb08434> in <module>()
      1 im = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
----> 2 bokeh.io.show(bebi103.viz.im_click(im))

~/anaconda3/lib/python3.6/site-packages/bebi103/viz.py in im_click(im, color_mapper, plot_height, plot_width, length_units, interpixel_distance, x_range, y_range, no_ticks, x_axis_label, y_axis_label, title, flip)
   2118 
   2119     div = bokeh.models.Div(width=200)
-> 2120     layout = bokeh.layout.row(p, div)
   2121 
   2122     p.js_on_event(bokeh.events.Tap, display_event(div, attributes=['x', 'y']))

AttributeError: module 'bokeh' has no attribute 'layout'

**Comment by justinbois** [comment]
Fixed in bleeding edge. Will be in subsequent release.
